export const ORACLE_CARDS = [
  "De Engel van Dageraad", "De Geest van de Eeuwige Eik", "De Nachtuil van Wijsheid", "De Gids van het Noorderlicht",
  "De Bewaarder van Tijd", "De Vlam van Transformatie", "De Fluisterende Rivier", "De Sterrenwever",
  "De Leeuw van Moed", "De Zwaan van Zuiverheid", "De Mystieke Dromenvanger", "De Aartsengel van Genezing",
  "De Witte Wolf van Instinct", "De Feniks van Wedergeboorte", "De Oceaan Priesteres", "De Danser van de Wind",
  "De Zilveren Maan", "De Gouden Zon", "De Hoeder van de Kristallen", "De Fluisteraar van Geheimen",
  "De Engel van Overvloed", "De Draak van Oude Wijsheid", "De Spirituele Krijger", "De Spiegel van de Ziel",
  "De Roos van Onvoorwaardelijke Liefde", "De Adelaar van Visie", "De Tijger van Kracht", "De Vallei van Stilte",
  "De Brug van Licht", "De Schaduw Wacht", "De Zang van de Walvis", "De Bloesem van Geduld",
  "De Poortwachter van de Kosmos", "De Lotus van Ontwaking", "De Engel van Vreugde", "De Geest van het Woud",
  "De Steen der Waarheid", "De Vlinder van Verandering", "De Eenhoorn van Magie", "De Doolhof van Illusie",
  "De Uil van Helderziendheid", "De Gouden Sleutel", "De Wachter van de Drempel", "De Stroom van Genade",
  "De Engel van Troost", "De Vos van Slimheid", "De Beer van Bescherming", "De Berg van Standvastigheid",
  "De Druppel van Leven", "De Dansende Vuurgeest", "De Hoeder van het Vuur", "De Zachte Bries",
  "De Heilige Geometrie", "De Bron van Creativiteit", "De Engel van Hoop", "De Zwarte panter van Mysterie",
  "De Stille Observeerder", "De Veer van Geloof", "De Knoop van Verbinding", "De Parel van Wijsheid",
  "De Boom des Levens", "De Zandloper van Lot", "De Schildpad van Aarding", "De Engel van Wonderen"
];

export const CARD_MEANINGS: Record<string, string> = {
  "De Engel van Dageraad": "Een nieuw begin breekt aan; omarm de frisse energie van de ochtend. Laat de schaduwen van gisteren achter je.",
  "De Geest van de Eeuwige Eik": "Vind je wortels en sta stevig. Geduld en kracht zullen je door deze fase leiden.",
  "De Nachtuil van Wijsheid": "Vertrouw op je intuïtie, de antwoorden liggen in de stilte van de nacht verborgen.",
  "De Gids van het Noorderlicht": "Magie is overal om je heen; volg het innerlijke licht dat je de weg wijst.",
  "De Bewaarder van Tijd": "Alles gebeurt op het juiste kosmische moment. Forceer niets, maar wees geduldig.",
  "De Vlam van Transformatie": "Laat los wat je niet langer dient. Uit de as herrijst een vernieuwd en sterker zelf.",
  "De Fluisterende Rivier": "Strijd niet tegen de stroom in; laat je meevoeren door het ritme van het leven.",
  "De Sterrenwever": "Jij bent de ontwerper van je eigen lot. Weef je dromen actief tot realiteit.",
  "De Leeuw van Moed": "Verzamel je innerlijke oerkracht en sta moedig voor je ware overtuigingen.",
  "De Zwaan van Zuiverheid": "Innerlijke schoonheid, oprechtheid en compassie zijn je meest krachtige wapens.",
  "De Mystieke Dromenvanger": "Je dromen bevatten belangrijke, subtiele boodschappen. Luister goed naar je onderbewustzijn.",
  "De Aartsengel van Genezing": "Helende energie omringt je; sta wagenwijd open voor fysiek en emotioneel herstel.",
  "De Witte Wolf van Instinct": "Vertrouw onvoorwaardelijk op je oerinstinct; je innerlijke kompas wijst feilloos de weg.",
  "De Feniks van Wedergeboorte": "Uit een uitdagende, moeilijke periode zal een ongelooflijk krachtig nieuw begin ontstaan.",
  "De Oceaan Priesteres": "Duik diep in het water van je emoties; de wezenlijke antwoorden liggen in de diepte.",
  "De Danser van de Wind": "Beweeg flexibel en dynamisch mee met de plotselinge veranderingen op je pad.",
  "De Zilveren Maan": "Ontdek je zachte, intuïtieve kant. Luister naar je vrouwelijke creatieve energie.",
  "De Gouden Zon": "Levenskracht, warmte en een rijke overvloed stralen je tegemoet. Het is jouw tijd om te schitteren.",
  "De Hoeder van de Kristallen": "Zoek naar zuivere helderheid en structuur temidden van opkomende chaos.",
  "De Fluisteraar van Geheimen": "Wees discreet en naar binnen gekeerd. Niet alles hoeft direct met de buitenwereld gedeeld te worden.",
  "De Engel van Overvloed": "Het universum zorgt liefdevol voor je; verwacht een onverwachte stroom van zegeningen.",
  "De Draak van Oude Wijsheid": "Bescherm wat je ten diepste dierbaar is en gebruik je opgebouwde levenslessen.",
  "De Spirituele Krijger": "Blijf standvastig vechten voor de waarheid met liefde in plaats van boosheid als je belangrijkste wapen.",
  "De Spiegel van de Ziel": "Wat je aantrekt of irriteert in anderen, is een directe reflectie van processen in jezelf.",
  "De Roos van Onvoorwaardelijke Liefde": "Open je hart volledig. Liefde is de hoogste en meest genezende vibratie van de kosmos.",
  "De Adelaar van Visie": "Neem bewust afstand; door de situatie vanuit een overkoepelend vogelperspectief te bekijken ontstaat begrip.",
  "De Tijger van Kracht": "Laat je rauwe passie en ongedimde innerlijke vuur naar de buitenwereld treden.",
  "De Vallei van Stilte": "Trek je terug in de rust; in de stille leegte vind je luid en duidelijk je antwoorden.",
  "De Brug van Licht": "Je maakt momenteel een uiterst cruciale overgang naar een wezenlijk hoger bewustzijn door.",
  "De Schaduw Wacht": "Confronteer liefdevol de delen van jezelf die je liever verbergt om weer compleet heel te worden.",
  "De Zang van de Walvis": "Luister naar de oeroude roep van je ziel en je aller diepste wezenlijke verlangens.",
  "De Bloesem van Geduld": "Processen forceren heeft nu geen enkele zin; laat de dingen op hun eigen perfecte tempo natuurlijkerwijs bloeien.",
  "De Poortwachter van de Kosmos": "Compleet nieuwe, wonderbaarlijke spirituele dimensies en deuren openen zich nu voor je.",
  "De Lotus van Ontwaking": "Zelfs uit de aller donkerste modder ontstaat uiteindelijk de allermooiste, zuivere groei.",
  "De Engel van Vreugde": "Vier de magie van het leven. Lach, dans onbezorgd en vind intens plezier in de allerkleinste dingen.",
  "De Geest van het Woud": "Maak de tijd om je te verbinden met de natuurgrond; dit is nodig om jezelf diep te aarden en te herladen.",
  "De Steen der Waarheid": "Spreek onverschrokken je eigen, authentieke levenswaarheid uit, wat anderen daar ook van mogen verwachten.",
  "De Vlinder van Verandering": "Een diepe transformatie is gaande. Heb een ijzersterk vertrouwen in het proces van je eigen metamorfose.",
  "De Eenhoorn van Magie": "Blijf koppig en volhardend geloven in wonderen; het volslagen onmogelijke staat op het punt realiteit te worden.",
  "De Doolhof van Illusie": "Kijk heel goed en wees enorm kritisch - de huidige situatie is complexer dan deze op het eerste gezicht lijkt.",
  "De Uil van Helderziendheid": "Je unieke vermogen om dwars door illusies heen de waarheid te voelen groeit immens snel.",
  "De Gouden Sleutel": "Zoek niet langer; je hebt de gouden oplossing voor je huidige probleem al stevig in je eigen handen.",
  "De Wachter van de Drempel": "Zodra je je grootste existentiële angst overwint, zul je in één klap je ware potentieel permanent ontgrendelen.",
  "De Stroom van Genade": "Vergeef resoluut jezelf en de onwetendheid van anderen; pas dit besluit bevrijdt je vastzittende energie.",
  "De Engel van Troost": "Vergeet nooit: je bent niet alleen. Bij wezenlijk verdriet of pijn word je volop bedekt met onzichtbare steun.",
  "De Vos van Slimheid": "Gebruik nu je scherpe intellect; wees uiterst tactisch en uiterst strategisch in de belangrijke keuzes waartoe je nu geroepen bent.",
  "De Beer van Bescherming": "Creëer een resolute, volstrekt duidelijke en onvermurwbare veilige heilige grens voor je kwetsbare zelf en waak over je intimi.",
  "De Berg van Standvastigheid": "Blijf onbeweeglijk vastberaden en ongeëvenaard stevig staan; je kunt en zult dit taaie langdurige obstakel met glorieus gemak te boven komen.",
  "De Druppel van Leven": "Herinner jezelf er dagelijks aan dat nota bene de aller, állerkleinste schijnbaar onbetekenende actie altijd onnoemelijk grote causale rimpelingen veroorzaakt.",
  "De Dansende Vuurgeest": "Voed vandaag bewust en met volle overgave je immense brandende zee van aangeboren potentie voor ontembare en speelse creativiteit.",
  "De Hoeder van het Vuur": "Verwaarloos of relativeer je grootste passies niet, maar wek en bewaak continu je zielsdoel vurig en laat je ontembare en tomeloze wilde innerlijke vuur niet langzaam maar zeker zomaar ongemerkt doven door anderen.",
  "De Zachte Bries": "Ontspan nu; een zeldzaam verfrissende, gelukzalige zachte wending en aangename, haast onopgemerkte positieve opfrissing van gemoed, sfeer, en veranderende gelukkige levensveranderende wending komt onverwachts vliegensvlug in volle overgave vredig en wel jouw kant op.",
  "De Heilige Geometrie": "Achter of beter gezegd, in en dwars door alle toevalligheden die jij in je roerige rumoerige en hectische uiterlijke leven aantreft en op dit specifieke eigen moment lijdzaam probeert te bevatten of te begrijpen, is direct werkzaam een uiterst intelligent fenomenaal wiskundig briljant logisch en daadkrachtig ingenieus constructieplan of te wel absoluut feilloze perfect en tevens magistraal weelderig goddelijk wonder boven wonder ontworpen levensplan uitsluitend en volledig ten gunste van jouw en ieders wezenlijke ontwaking.",
  "De Bron van Creativiteit": "Wees er gerust ten diepste en fundamenteel de bewuste eigenaar van; je wezenlijk verankerde originele ik bent te allen tijde onverbrekelijk voorgoed non lokaal verbonden met the pure pure fundamentele absolute open en niet een, oneindige intelligente stroom zowaar en onmiskenbaar vol met zuivere levensscheppende inspiratiekracht en verrichte ideeën. Uit jezelf zacht of extreem luidkeels maar theatraal onbeperkt voluit!",
  "De Engel van Hoop": "Neem volkomen geruststelling en moed eruit op; net alsof exact juist uiterst en enkel daar en wanneer de totale uiterste peilloos diepe allerdonkerste inktzwarte ijzingwekkende nacht the boventoon uiterst regeert, en paniek lijkt te winnen over al te overzien, is absoluut een onaantastbare ontiegelijk onaantastbaar fonkelende hoopvolle, stralingskrachtige overtuigende blije kleine twinkelende geruststellende schittering van warm, vol vertrouwen of wel goudkleurig levensreddend sprankelend verlossend oplichtend piepkleine ster of met andere woorden het allereerste veelbeduidende ultieme gloren, het veel geruststellende dagend lichtpuntje aan de einder waarneembaar met ongeëvenaard krachtig hoopvol opbouwend geruststellende effect ten gehore gebracht en dus immer altijd daar ergens absoluut immer vol optimisme levend op of glooiend opkomend net aan precies stralingskrachtig over en of aan de ultieme verste rimpelloze horizon der ervaring altijd voor je te aanschouwen.",
  "De Zwarte panter van Mysterie": "Vaar blindelings maar veilig het oeverloos onbekende diepe duistere mysterie van wat morgen misschien brengen zal in; alles is onder sublieme controle.",
  "De Stille Observeerder": "Breek vandaag zachtjes jouw patroon; neem liever voor één keer geen onmiddellijke reactieve daadkrachtige actie; pauzeer, adem rustig en bekijk je alledaagse en de ongewone wereld plus dus deze of andere specifieke actuele verwarrende situatie heel aandachtig doch sereen rustig vanuit louter of enkel en uitsluitend de onbeteiligde positie of de ontzagwekkende sereniteit verhullende neutrale beschouwende positie vanaf ergens in den verte of in de verhulde zijlijn.",
  "De Veer van Geloof": "Oefen vandaag nog het immense magische geruststellende of haast wonderbaarlijke rotsvaste zekere en troostende grootse kalmerende en rust en kalmte brengend diepe uiterste fundamentele in zichzelf gedragen kalme basis pure pure geloof dat ongeacht alle tegengestelde signalen of uitwijkpogingen dit exacte huidige soms verwarrende schijnbare of althans hobbelige grillige gekozen overtuiging of the pas exact bewandelde uiterste soms zelfs pijnlijke, lastige al the min en in theorie zwaar verwerpelijke lijdensweg uiteindelijk zonder ook maar enig minuscuul twijfel the juiste bleek en is.",
  "De Knoop van Verbinding": "Je bent op diep niveau met alles en iedereen verbonden; je kleine acties hebben een enorme rimpel impact op het grote geheel.",
  "De Parel van Wijsheid": "Inzichten van werkelijk zuivere glanzende onschatbare levenswaarde groeiden uit eerdere belemmeringen en worstelingen. Koester deze wijsheid als een kostbare parel.",
  "De Boom des Levens": "Je zuivere bestaansrecht ontkiemt direct stevig vanuit verbinding; je bent een waardevol, onmisbaar en prachtig onderdeel van een immens goddelijk weefsel.",
  "De Zandloper van Lot": "Elke inspanning om de tijd wezenlijk te beïnvloeden of te forceren is tevergeefs. Heb geduld, want alles volgt een perfecte universele tijdslijn.",
  "De Schildpad van Aarding": "Kalmte en een rustig, aards en systematisch tempo behaalt absoluut de triomfantelijke winst. Vind rust, vertraag je tempo en voel je veilig.",
  "De Engel van Wonderen": "Stel je onvoorwaardelijk open en anticipeer in een blij, puur en open vertrouwen op de naderende komst van een fonkelend en onverklaarbaar wonder."
};

export const getRandomCard = () => {
  const randomIndex = Math.floor(Math.random() * ORACLE_CARDS.length);
  return ORACLE_CARDS[randomIndex];
};
